<a href="https://colab.research.google.com/github/ggmmi1/class/blob/main/20241213.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy
import numpy as np
x = np.array([3,1,2])
print(x)
print(type(x))
print(type([3,1,2]))

In [ ]:
#실습
c = [[1],[1,2]]
d = np.array(([1,1],[1,2]))

for x,y in d:
  print(x,y)

In [ ]:
#넘파이의 산술연산
import numpy as np

x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

In [ ]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])

print(a.ndim)
print(a.shape)

a = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])

print(a.ndim)
print(a.shape)

a = np.array([[[1,2],[2,2]],[[3,2],[4,2]],[[5,2],[6,2]]])

print(a.ndim)
print(a.shape) #큰상자 3개 안에, 작은상자 2개 있고, 그 안에 원소 2개가 있으니까 (3,2,2)

a = np.array([[[[1],[2]],[[2],[2]]],[[[3],[2]],[[4],[2]]],[[[5],[2]],[[6],[2]]]])

print(a.ndim)
print(a.shape)

2
(3, 2)
3
(3, 2, 1)
3
(3, 2, 2)
4
(3, 2, 2, 1)


In [9]:
np.dot(4,2)

ndar1 = np.array([3,2])
ndar2 = np.array([4,6])
np.dot(ndar1, ndar2)

24

In [11]:
ndar1 = np.array([[1,2],[3,4]])
ndar2 = np.array([[1,2],[3,4]])
np.dot(ndar1, ndar2)

array([[ 7, 10],
       [15, 22]])

In [16]:
#flatten
ndar2 = np.array([[1,2],[3,4]])
ndar2.flatten() #평탄화 작업 N차원 배열을 1차원 배열로 변환

#flatten 2
ndar2 = np.array([[[1],[2]],[[3],[4]]])
print(ndar2.shape)
print(ndar2.ndim)
a = ndar2.flatten()
print(a.ndim)
print(ndar2)

(2, 2, 1)
3
1
[[[1]
  [2]]

 [[3]
  [4]]]


In [21]:
#.reshape():배열의 차원을 변경
ndarr = np.array([[1,2],[2,3],[3,4]])
ndarr.reshape(2,3)


array([[1, 2, 2],
       [3, 3, 4]])

In [23]:
ndarr.reshape(6,1)

array([[1],
       [2],
       [2],
       [3],
       [3],
       [4]])

In [25]:
ndarr.reshape(1,6)

array([[1, 2, 2, 3, 3, 4]])

In [27]:
#random
np.random.randint(5, size=(2,4))


array([[2, 4, 0, 1],
       [2, 2, 1, 0]])

In [32]:
np.random.rand(2,3)

array([[0.86621283, 0.79016242, 0.88604465],
       [0.84831499, 0.00994466, 0.43295942]])

In [34]:
rng = np.random.default_rng()
rng.random()

0.015174972691899269

In [37]:
rng.integers(0, 10, (2,4))

array([[3, 2, 3, 7],
       [9, 0, 4, 6]])

In [39]:
ndarr = np.array([[6,3],[5,2],[4,1]])
ndarr > 4

array([[ True, False],
       [ True, False],
       [False, False]])

In [43]:
ndarr = np.array([[6,3],[5,2],[4,1]])
ndarr[ndarr>=4]

array([6, 5, 4])