<a href="https://colab.research.google.com/github/ggmmi1/class/blob/main/20241214.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
#실습 Numpy 모듈 사용해보기 1-1
#1 10개의 0으로 채워진 array를 만들고 출력해주세요
#2 1먼에서 만들어진 array에서 5번째 값을 1로 바꾸고 출력해주세요
#3 10부터 30까지의 수로 이루어진 array를 만들고 출력해주세요
#4 0부터 99까지의 난수로 이루어진 2x2 array를 만들고 출력해주세요
#5 0부터 1 사이의 난수로 이루어진 2x4 array를 만들고 출력해주새요
import numpy as np
a = np.zeros(10) #1
print(a)
#2
a[4] = 1
print(a)
#3
b = np.arange(10,31)
print(b)
#4
c = np.random.randint(0, 100, (2, 2)) #integers 대신 사용해도 됨 , rng = np.random.default_rng(n) n값이 있어야 랜덤 숫자 고정!, 없으면 계쏙 랜덤으로 나옴
print(c)
#5
d = np.random.rand(2, 4)
print(d)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[[81 83]
 [92 69]]
[[0.81738693 0.36034733 0.39895207 0.87498713]
 [0.72187485 0.50343834 0.84587069 0.67425693]]


In [53]:
#실습 Numpy 모듈 사용해보기 1-2
#6 35부터 74까지의 순차적인 수로 이루어진 1차원 배열을 만들고 10x44 행렬로 변환 후 출력해주세요.
#7 6번에서 만든 배열을 맨 끝의 행부터 역순으로 출력해주세요
#8 6번에서 만든 배열 중 두 번째 행부터 마지막 직전 행까지, 세번째 열부터 마지막 열까지 슬라이싱해서 출력해주세요
#9 6번에서 만든 배열에서 마지막 열에 해당하는 모든 값을 출력해주세요(1차원 배열로)
#10 9-1번에서 만든 배열을 역순으로 정렬해서 출력해주세요
#11 1부터 50까지의 난수로 된 5x6 배열을 만들고, 배열에서 짝수만 선택하여 출력하는 코드를 작성하세요

import numpy as np
e = np.arange(35, 75) #6
f = e.reshape(10, 4)
print(f)
#7
for row in f[::-1]:
    print(row)
#8
g = f[1:-1, 2:]
print(g)

#9
last = f[:, -1]
print(last)

#9-1
print(last.reshape(-1, 1))  #다른 방법 lsat_1 = f[:, -1], print(last_1)

#10
print(last[::-1].reshape(-1, 1)) #다른 방법 an10 = f [::-1, -1:]

#11
h = np.random.randint(1, 51,(5, 6)) #다른 방법 ndarr = rng.integers(1, 51, size=(5,6))
print(h)                            #print(ndarr)
i = h[h % 2 == 0]                   #print(ndarr[ndarr%2 == 0])
print("짝수만 출력", i)


[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]
[71 72 73 74]
[67 68 69 70]
[63 64 65 66]
[59 60 61 62]
[55 56 57 58]
[51 52 53 54]
[47 48 49 50]
[43 44 45 46]
[39 40 41 42]
[35 36 37 38]
[[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]
[38 42 46 50 54 58 62 66 70 74]
[[38]
 [42]
 [46]
 [50]
 [54]
 [58]
 [62]
 [66]
 [70]
 [74]]
[[74]
 [70]
 [66]
 [62]
 [58]
 [54]
 [50]
 [46]
 [42]
 [38]]
[[23  3 16 16 46 44]
 [21 36 48 27 20 12]
 [13 29  1 29 24 12]
 [28 43 22 15 12  6]
 [16 19 15 15 39 31]]
짝수만 출력 [16 16 46 44 36 48 20 12 24 12 28 22 12  6 16]


In [55]:
#차원 확장
import numpy as np
a = np.array([[1,2],[3,4]])

expanded = np.expand_dims(a, 2)
print(expanded)
print(expanded.shape)


[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


In [57]:
expanded = np.expand_dims(a, 1)
print(expanded)
print(expanded.shape)

[[[1 2]]

 [[3 4]]]
(2, 1, 2)


In [60]:
#차원 축소
np_ones = np.ones((1,2,1,3))
print(np_ones)

squeezed = np.squeeze(np_ones, 0)
print(squeezed)
print(squeezed.shape)

[[[[1. 1. 1.]]

  [[1. 1. 1.]]]]
[[[1. 1. 1.]]

 [[1. 1. 1.]]]
(2, 1, 3)


In [73]:
a = [1,2,2,3,3,3,4,4]
u_a, indexs, counts = np.unique(a, return_index = True, return_counts = True)
print(u_a)
print(indexs)
print(counts)


[1 2 3 4]
[0 1 3 6]
[1 2 3 2]


In [74]:
def add (a=1, b=1):
  return a,b,a+b
a,b,sum = add(2,3)
print(a, b, sum)

2 3 5


In [75]:
def add (a=1, b=1):
  return a,b,a+b
sum, a, b = add(2,3)
print(a, b, sum)

3 5 2


In [77]:
#정렬
a = np.array([1,4,2,3])
b = np.sort(a)
print(f"a {a}")
print(f"b {b}")
c = np.argsort(a) #중요 인덱스 반환
print(f"c {c}")
print(f"cc {a[c]}")
a.sort()
print(f"a{a}")

a [1 4 2 3]
b [1 2 3 4]
c [0 2 3 1]
cc [1 2 3 4]
a[1 2 3 4]


In [82]:
#그 밖 함수
#np.mean 평균값
a = np.array([1,4,2,3])
np.mean(a)

2.5

In [83]:
np.std(a) #표준편차

1.118033988749895

In [86]:
np.var(a) #분산

1.25

In [87]:
np.max(a) #최댓값

4

In [89]:
np.min(a) #최솟값

1

In [90]:
np.sum(a) #합

10

In [92]:
np.prod(a) #곱

24

In [94]:
np.median(a) #중앙값

2.5

In [103]:
# (axis=1) axis=1 열을 나타냄 ,  axis=0 행을 나타냄  만약 max이용 했으면 각자 열, 행마다 큰 값이 나옴
import numpy as np

x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99
print(x)

[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]


In [105]:
a = np.sort(x, axis=0)
print(a)

[[-99   1 -99   3 -99]
 [-99   6 -99   8 -99]
 [  0  11   2  13   4]]


In [107]:
a = np.sort(x, axis=1)
print(a)

[[  0   1   2   3   4]
 [-99 -99 -99   6   8]
 [-99 -99 -99  11  13]]


In [112]:
#실습 Numpy 모듈 사용해보기 2
# [1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100]
#1 중복을 제거한 배열 출력
#2 1의 결과의 최대,최소,평균값 출력
#3 1의 결과의 모든 합 출력
#4 중복을 제거하지 않은 배열의 중간값 출력

a = [1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100]
u_a = np.unique(a) #1
print(u_a)

#2
np.max(a)
np.min(a)

[  1   2   3   4   5   7   8   9  10  11  24 100]


1

In [114]:
np.mean(a)

12.5

In [116]:
#3
np.sum(a)

200

In [118]:
#4
np.median(a)

5.0

In [159]:
#실습 Numpy 모듈 사용해보기 3
# x = np.arange(15, dtype=np.int64.reshape(3,5))
# x[1:, ::2] = -99
#1 1열의 최대, 최소, 평균값 출력
#2 2행의 모든 합 출력
#3 실습 2번 1차원 배열을 argsort 이용하여 내림차순 정렬

import numpy as np

x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99
print(x)
#1
print(np.max(x[:,0]))
print(np.min(x[:,0]))
print(np.mean(x[:,0]))
#2
print(np.sum(x[1]))
#3
a = np.array([1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100])
b = np.argsort(a)
print(a[b[::-1]])

[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]
0
-99
-66.0
-283
[100  24  11  10   9   8   7   5   5   5   5   4   3   2   1   1]
